### ISSUE TITLE
Print :DEPENDS-ON vertically

### ISSUE THREAD

**Issue by phoe** [phoe-krk/asd-generator#4]
Hey @guicho271828 - could you perhaps help me with pretty-printing the :DEPENDS-ON in a vertical manner?

Right now, it's being printed as a single line:

``` lisp
 :depends-on (#:hu.dwim.defclass-star #:ironclad #:cl-colors #:jpl-queues #:alexandria #:bordeaux-threads #:usocket #:flexi-streams)
```

And I'd prefer it to be printed as:

``` lisp
:depends-on (#:hu.dwim.defclass-star
             #:ironclad
             #:cl-colors
             #:jpl-queues
             #:alexandria
             #:bordeaux-threads
             #:usocket
             #:flexi-streams)
```

Regards
~phoe

**Comment by guicho271828** [comment]
wrap it in pprint-logical-block and use `(pprint :mandatory)` instead of `(terpri)` or alike.

**Comment by phoe** [comment]
Thanks. I copied the :COMPONENTS part and it works now.
